name: "TypoCheck"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - name: TypoCheck
      uses: typoci/spellcheck-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}